### ISSUE TITLE
generate fr and de - 11630

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/active-iq-unified-manager-911#3]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-gudugunti** [comment]
@ntap-bmegan This repo is a recent entry. Could you let me know the dictionary size?

**Comment by ntap-bmegan** [comment]
Huh. That was unexpected, since I generated the list of repos using the list of JA repos. Must have timed it just perfectly. I've added it to the title and project metadata.
